server {
    listen 443 ssl;
    server_name localhost;

    # Nginx will look for the certs inside the container at these paths
    ssl_certificate /etc/nginx/certs/local.crt;
    ssl_certificate_key /etc/nginx/certs/local.key;

    location / {
        default_type text/plain;
        return 200 "HTTPS is working perfectly. Your local Dev environment is fully operational!\n";
    }
}